language: java

cache:
  directories:
    - .gradle
    - build

before_install:
- chmod +x gradlew

jobs:
  include:
  - stage: Build
    name: Build
    script: ./gradlew build -x test
  - stage: Test
    name: Test
    script: ./gradlew test --stacktrace --debug